/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets */
        get: operations["presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_api_recipe_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Audio */
        Audio: {
            /**
             * Mode
             * @default keep
             * @enum {string}
             */
            mode: "keep" | "mute" | "extract";
            /** Extract Format */
            extract_format?: ("aac" | "mp3" | "wav" | "flac" | "ogg") | null;
        };
        /** Bitrate */
        Bitrate: {
            /** Video Kbps */
            video_kbps?: number | null;
            /** Audio Kbps */
            audio_kbps?: number | null;
        };
        /** Crop */
        Crop: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
        };
        /** FrameCapture */
        FrameCapture: {
            /** At Ms */
            at_ms: number;
            /**
             * Format
             * @default png
             * @constant
             */
            format: "png";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanResponse */
        PlanResponse: {
            /** Mode */
            mode: string;
            /** Container */
            container: string;
            /** Ffmpeg Args */
            ffmpeg_args: string[];
            /** Outputs */
            outputs: Record<string, never>[];
        };
        /** Recipe */
        Recipe: {
            trim?: components["schemas"]["Trim"] | null;
            /** Remove Segments */
            remove_segments?: components["schemas"]["Segment"][];
            crop?: components["schemas"]["Crop"] | null;
            scale?: components["schemas"]["Scale"] | null;
            bitrate?: components["schemas"]["Bitrate"] | null;
            audio?: components["schemas"]["Audio"] | null;
            frame_capture?: components["schemas"]["FrameCapture"] | null;
            /**
             * Container
             * @default mp4
             * @enum {string}
             */
            container: "mp4" | "webm" | "mkv";
        };
        /** Scale */
        Scale: {
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /**
             * Keep Aspect
             * @default true
             */
            keep_aspect: boolean;
        };
        /** Segment */
        Segment: {
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
        };
        /** Trim */
        Trim: {
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms?: number | null;
        };
        /** ValidateRequest */
        ValidateRequest: {
            meta: components["schemas"]["VideoMeta"];
            recipe: components["schemas"]["Recipe"];
        };
        /** ValidateResponse */
        ValidateResponse: {
            /** Ok */
            ok: boolean;
            normalized: components["schemas"]["Recipe"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoMeta */
        VideoMeta: {
            /** Duration Ms */
            duration_ms: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Fps */
            fps: number;
            /**
             * Has Audio
             * @default true
             */
            has_audio: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    validate_api_recipe_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
